name: CI - Unit, Integration and End-to-End Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./api

      - name: Set up Docker Compose
        run: docker-compose up -d
        working-directory: .
        
      - name: Wait for Redis to be ready
        run: |
          until docker exec redis-star-wars redis-cli ping | grep -q PONG; do
            echo "Waiting for Redis to be ready..."
            sleep 2
          done
          echo "Redis is ready!"

      - name: Run Unit Tests
        run: npm run test:unit
        working-directory: ./api

      - name: Run Integration Tests
        run: npm run test:integration
        working-directory: ./api

      - name: Run End-to-End Tests
        run: npm run test:e2e
        working-directory: ./api

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down
        working-directory: .
